### ISSUE TITLE
Git projects block to include on participants page

### ISSUE THREAD

**Issue by VinceW** [MADspace/MADspace.github.io#35]
Participants can have their own participants page.

On the page of Joost Hoeks at: http://www.stichtingmadspace.nl/participants/joost_hoeks.html is a piece of (javascript) code which generates an overview of his github projects.

The idea is to have this code in an include block so it can be included on all participants pages.

The block needs to be generic, in such a way it takes a github name of a participant and then displays the projects (preferably in bootstrap table layout) 

If there is no github name of the participant, the block displays nothing :-)

**Comment by joosthoeks** [comment]
Done

**Comment by VinceW** [comment]
Is fixed in https://github.com/MADspace/MADspace.github.io/pull/38 so closing this issue
