### ISSUE TITLE
Move content from old sites

### ISSUE THREAD

**Issue by VinceW** [MADspace/MADspace.github.io#4]
The content on the old sites need to be integrated into the new site.

Old sites are:
- https://madspace.github.io/ (github pagina van stichtingmadspace.nl)
- https://madspace.nl (huidige site in wordpress)
- https://wiki.madspace.nl/doku.php (oude wiki)

**Comment by htdebeer** [comment]
Can you give or point to a short manual or set of guidelines how to do that? Then everyone can join in. Particularly for the personal wiki pages.

Maybe place it on the new website :-)

**Comment by VinceW** [comment]
I've created issue #8 for this :-). 
In other words ... It's on the todo list.

**Comment by htdebeer** [comment]
Awesome! 

And yes, I should start reading these messages in sequence :-)

**Comment by joosthoeks** [comment]
A long time ago
