### ISSUE TITLE
Menu; bigger font & color white

### ISSUE THREAD

**Issue by SweetDonky** [MADspace/MADspace.github.io#43]
On the current madspace.nl website the top menu is with a bigger font and in white, can this also be done with the new website to increase visibility?
![top menu madspace_nl](https://user-images.githubusercontent.com/35078384/38759306-8becb088-3f75-11e8-81a1-6d0a38246429.jpg)

**Comment by SweetDonky** [comment]
Font is white and a bit bigger now, a lot more readeble.
Only when hovering over, I think the font should change to black (as the background switches to white-ish). Still looking where I can change this in CSS...

**Comment by joosthoeks** [comment]
Looks good already
