### ISSUE TITLE
Theming new website

### ISSUE THREAD

**Issue by VinceW** [MADspace/MADspace.github.io#5]
Do we want keep the current theming or, something new?

**Comment by htdebeer** [comment]
We did not spend much though on the current theme, so any changes and improvements are fine.

**Comment by VinceW** [comment]
@SweetDonky can you open a new issue for this? 
And also label it with enhancement and theming?

Saves a lot of work when doing some triage on the issues.
tnx

**Comment by SweetDonky** [comment]
@VinceW it has been done!

**Comment by joosthoeks** [comment]
Finished
