### ISSUE TITLE
madspace.nl

### ISSUE THREAD

**Issue by SweetDonky** [MADspace/MADspace.github.io#55]
Er zijn nu nog 2 website's:

- madspace.nl
- stichtingmadspace.nl

Lijkt mij dat alles straks madspace.nl moet worden als primair domein?
Wat zou hiervoor nog moeten gebeuren?

**Comment by VinceW** [comment]
The website of madspace is available on: https://www.madspace.nl (with a valid https certificate)

I'm going to close this issue. Issue #62 is not completely resolved, but that issue can exist on it's own.
