### ISSUE TITLE
SSL certificaat stichtingmadspace.nl

### ISSUE THREAD

**Issue by SweetDonky** [MADspace/MADspace.github.io#56]
SSL certificaat dat wordt aangeboden op https://www.stichtingmadspace.nl/ verwijst naar Github.
Is het technisch mogelijk om een eigen SSL certificaat toe te passen?

Help page(s):
- https://help.github.com/articles/securing-your-github-pages-site-with-https/
- https://help.github.com/articles/troubleshooting-custom-domains/

**Comment by VinceW** [comment]
Not an issue anymore since https://www.madspace.nl is in place now.

**Comment by VinceW** [comment]
add reference to issue #55
